import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "./ClientProvider";
import { Toaster } from "react-hot-toast";
import SessionHydrator from "@/components/SessionHydrator";
import UserHydrator from "@/components/UserHydrator";
import AppShell from "./AppShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AGBase – AI Assistant for Your App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        data-theme="dark"
        cz-shortcut-listen="true"
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <ClientProvider>
            <SessionHydrator />
            <UserHydrator />
            <AppShell>
              {children}
            </AppShell>
            <Toaster position="top-center" reverseOrder={false} />
        </ClientProvider>
      </body>
    </html>
  );
}
